### PR TITLE
Work around Composer multi-version loading hack using a "V2" namespace

### LINKED ISSUE #205: Update throws php-error
I Have 2 drupal sites using composer2.0 and in thee require I have wikimedia/composer-merge plugin.
Today, on uodating the sites with composer update, composer merge plugin causes following errors:

PHP Fatal error:  Uncaught Error: Call to undefined method Wikimedia\Composer\Merge\ExtraPackage::getMergedRequirements() in phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code:287
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code(254): Wikimedia\Composer\MergePlugin_composer_tmp0->mergeFile(Object(Composer\Package\RootPackage), 'modules/contrib...')
#1 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code(215): Wikimedia\Composer\MergePlugin_composer_tmp0->mergeFiles(Array, false)
#2 [internal function]: Wikimedia\Composer\MergePlugin_composer_tmp0->onInstallUpdateOrDump(Object(Composer\Script\Event))
#3 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(173): call_user_func(Array, Object(Composer\Script\Event))
#4 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(101): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#5 phar:///usr/bi in phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code on line 287

Fatal error: Uncaught Error: Call to undefined method Wikimedia\Composer\Merge\ExtraPackage::getMergedRequirements() in phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code:287
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code(254): Wikimedia\Composer\MergePlugin_composer_tmp0->mergeFile(Object(Composer\Package\RootPackage), 'modules/contrib...')
#1 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code(215): Wikimedia\Composer\MergePlugin_composer_tmp0->mergeFiles(Array, false)
#2 [internal function]: Wikimedia\Composer\MergePlugin_composer_tmp0->onInstallUpdateOrDump(Object(Composer\Script\Event))
#3 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(173): call_user_func(Array, Object(Composer\Script\Event))
#4 phar:///usr/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(101): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#5 phar:///usr/bi in phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(213) : eval()'d code on line 287

I must say that everything is still working  fine but somewhere there must be something wrong.

gtz, bart

### PR DESCRIPTION
**Pull request by tstarling**
Composer would try to load two versions of the same plugin, by reading the main plugin file and rewriting the class name. But this doesn't work if the plugin has multiple classes. It tries to run the new plugin class with old helper classes.

So:

* Move all classes to Wikimedia\Composer\Merge\V2. This includes classes that were previously in the parent namespace.
* Clean up unused "use" statements.

Note that the namespace version number will have to be incremented every time there is an internal interface change.

Closes #205

### CODE REVIEW

File: src/ExtraPackage.php [hunk 1]
```diff
@@ -346,7 +342,7 @@ protected function mergeConstraints(Link $origin, Link $merge, PluginState $stat
         $newPrettyString = $merge->getConstraint()->getPrettyString();
 
         if ($state->isComposer1()) {
-            $constraintClass = 'Wikimedia\\Composer\\Merge\\MultiConstraint';
+            $constraintClass = 'Wikimedia\\Composer\\Merge\\V2\\MultiConstraint';
```
Comment (reedy) [inline src/ExtraPackage.php:345]: Is it worth moving these to ::class (if they'll work) too?

Also, this looks kinda weird straight off; "if the state is composer (v) 1, use composer merge pluging V2 MultiConstraint, else use the one from Composer itself"

I know it's technically V2 of the plugin...

Comment (mcaskill) [reply src/ExtraPackage.php:345]: I agree with you that the `V2` namespace feels weird. Sort of a necessary evil.

If only the Merge plugin had provided support for `setUpdateAllowList()` early on (before work on Composer 2 even began) then we _might_ have been able to avoid the renamespacing.

**Review by mcaskill — COMMENTED** [review]
The only alternative to this approach would be to implement runtime class replacement like Composer does for the main plugin file (see [`/src/Composer/Plugin/PluginManager.php`](https://github.com/composer/composer/blob/40095b2/src/Composer/Plugin/PluginManager.php#L204-L223)).

What if we introduced a `Factory` class that could do that, if it detects a key method is missing?
In our situation `ExtraPackage::getMergedRequirement()` or `PluginState::isComposer1()`.

File: src/ExtraPackage.php (hunk 1 above)
Comment (tstarling) [reply src/ExtraPackage.php]: Done, used ::class. With ::class it's not necessary to reference V2 in this line of code.

**Comment by tstarling** [comment]
I'm not really interested in exploring alternative approaches, I just want to release it and move on to the next thing. This way is simple, it works, and it's done already. If @mcaskill approves then I'll merge and release it as 2.0.0.

File: composer.json [hunk 2]
```diff
@@ -23,14 +23,14 @@
     },
     "autoload": {
         "psr-4": {
-            "Wikimedia\\Composer\\": "src/"
+            "Wikimedia\\Composer\\Merge\\V2\\": "src/"
         }
     },
     "extra": {
         "branch-alias": {
             "dev-master": "1.5.x-dev"
```
Comment (mcaskill) [inline composer.json:31]:
```suggestion
             "dev-master": "2.x-dev"
```

**Review by mcaskill — CHANGES_REQUESTED** [review]

**Review by mcaskill — APPROVED** [review]

**Comment by tstarling** [comment]
I tagged "2.0.0" before I realised that "v2.0.0" would be the correct convention for this package (for other packages I have used the plain version number without the "v"). So I deleted the tag, deleted the package version from packagist, and tagged v2.0.0. I didn't see v2.0.0 in packagist, so I released the same commit as v2.0.1, expecting that packagist got confused about the deleted version. Both v2.0.0 and v2.0.1 did end up in packagist eventually.

The point is, this is released as 2.0.1, please test and enjoy.
